<div class="bg-partner-gray">
  <div class="centered">
    <div class="all-inline tj md-tc">
{% for item in module.group %}
	{% if item.client_logo.src %}
		{% set sizeAttrs = 'width="{{ item.client_logo.width }}" height="{{ item.client_logo.height }}"' %}
		{% if item.client_logo.size_type == 'auto' %}
			{% set sizeAttrs = 'style="max-width: 100%; height: auto;"' %}
		{% elif item.client_logo.size_type == 'auto_custom_max' %}
			{% set sizeAttrs = 'width="100%" height="auto" style="max-width: {{ item.client_logo.max_width }}px; max-height: {{ item.client_logo.max_height }}px"' %}
		{% endif %}
      <a href="{{ href }}"
		{% if item.link.open_in_new_tab %}target="_blank"{% endif %}
		{% if item.link.no_follow %}rel="nofollow"{% endif %}
		>
		<img src="{{ item.client_logo.src }}" alt="{{ item.client_logo.alt }}" {{ sizeAttrs }} class="pt40">
	</a>
		
	{% endif %}
{% endfor %}
    </div>
  </div>
</div>

